services:
  # serviço do banco de dados postgresql
  db:
    image: postgres:15
    container_name: visionqa_db
    environment:
      POSTGRES_DB: visionqa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
       #  inicialização da pasta
      - ./db:/docker-entrypoint-initdb.d
      # volume persistente para os dados do banco
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # mapeia porta do container para a máquina

  app:
    build: ./app  # constrói a imagem a partir do Dockerfile na pasta ./app 
    container_name: visionqa_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: visionqa
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "5000:5000" # mapeia porta da aplicação
    depends_on:
      - db  # só sobe depois que o banco estiver pronto

# volume compartilhado q define o nível raiz
volumes:
  postgres_data: